VERSION = ${mod_version}
MOD_ID = ${mod_id}
MOD_NAME = ${mod_name}

CLIENT_PROXY = com.lulan.${mod_id}.proxy.ClientProxy
SERVER_PROXY = com.lulan.${mod_id}.proxy.ServerProxy
TEXTURES_BLOCKS = ${mod_id}:textures/blocks/
TEXTURES_ENTITY = ${mod_id}:textures/entity/
TEXTURES_GUI = ${mod_id}:textures/gui/
TEXTURES_PARTICLE = ${mod_id}:textures/particles/
MOD_ID_Baubles = baubles
MOD_ID_IC2 = ic2
MOD_ID_Metamorph = metamorph